# Generated by Django 5.2.7 on 2025-11-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Стаж (лет)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='medical_specialization',
            field=models.CharField(blank=True, max_length=200, verbose_name='Медицинская специализация'),
        ),
    ]
